@baseUrl = http://127.0.0.1:8000
@token = 
@url_id = 1

### Register

POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
    "username": "test1",
    "email": "test1@example.com",
    "password": "password123"
}

### Login

POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
    "username": "test1",
    "password": "password123"
}

### Create URL

POST {{baseUrl}}/api/shorten/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "original_url":"https://github.com",
    "custom_alias": "Git"
}

### My URLs

GET {{baseUrl}}/api/my-urls/
Authorization: Bearer {{token}}

### Update URL

PATCH {{baseUrl}}/api/urls/{{url_id}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "original_url": "https://github.com/updated",
    "custom_alias": "arslan-git"
}

### Delete URL

DELETE {{baseUrl}}/api/urls/{{url_id}}/delete/
Authorization: Bearer {{token}}