# Generated by Django 5.2.15 on 2026-07-30 10:33

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_orginal_url_shorturl_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(db_index=True, default=shortener.models.generate_code, max_length=20, unique=True),
        ),
    ]
