# Generated by Django 5.2.15 on 2026-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_custom_alias_shorturl_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
